/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Orders API
 * API for managing orders and products
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
export interface Links {
  /** URL of the first page */
  first?: string;
  /** URL of the last page */
  last?: string;
  /**
   * URL of the previous page, null if on first page
   * @nullable
   */
  prev?: string | null;
  /**
   * URL of the next page, null if on last page
   * @nullable
   */
  next?: string | null;
}

export interface Product {
  /** Name of the product */
  name: string;
  /** Icon identifier for the product */
  icon: string;
  /**
   * Quantity of the product ordered
   * @minimum 1
   */
  quantity: number;
}

export interface ProductItem {
  id: number;
  /** Name of the product */
  name: string;
  icon: string;
  /**
   * Price (in cents)
   * @minimum 1
   */
  price: number;
}

export interface Order {
  id: number;
  /** Total price of the order in cents */
  price: number;
  trashed: boolean;
  trashable: boolean;
  /** Name of the user who placed the order */
  user: string;
  /** Timestamp of when the order was placed */
  date: string;
  /** List of products in the order */
  products: Product[];
}

export type GetApiOrdersParams = {
/**
 * Page number for pagination
 */
page?: number;
};

export type GetApiOrders200 = {
  data?: Order[];
  links?: Links;
};





/**
 * @summary Get all orders
 */
export const getGetApiOrdersUrl = (params?: GetApiOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/api/orders?${normalizedParams.toString()}` : `/api/orders`
}

export const getApiOrders = async (params?: GetApiOrdersParams, options?: RequestInit): Promise<GetApiOrders200> => {
  
  const res = await fetch(getGetApiOrdersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetApiOrders200 = body ? JSON.parse(body) : {}

  return data
}



export const getGetApiOrdersQueryKey = (params?: GetApiOrdersParams,) => {
    return [`/api/orders`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getApiOrders>>, TError = unknown>(params?: GetApiOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOrders>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiOrdersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiOrders>>> = ({ signal }) => getApiOrders(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiOrders>>>
export type GetApiOrdersQueryError = unknown


export function useGetApiOrders<TData = Awaited<ReturnType<typeof getApiOrders>>, TError = unknown>(
 params: undefined |  GetApiOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOrders>>,
          TError,
          Awaited<ReturnType<typeof getApiOrders>>
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOrders<TData = Awaited<ReturnType<typeof getApiOrders>>, TError = unknown>(
 params?: GetApiOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOrders>>,
          TError,
          Awaited<ReturnType<typeof getApiOrders>>
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOrders<TData = Awaited<ReturnType<typeof getApiOrders>>, TError = unknown>(
 params?: GetApiOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOrders>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all orders
 */

export function useGetApiOrders<TData = Awaited<ReturnType<typeof getApiOrders>>, TError = unknown>(
 params?: GetApiOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOrders>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete a specific order
 */
export const getDeleteApiOrdersOrderUrl = (order: number,) => {


  return `/api/orders/${order}`
}

export const deleteApiOrdersOrder = async (order: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getDeleteApiOrdersOrderUrl(order),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: void = body ? JSON.parse(body) : {}

  return data
}




export const getDeleteApiOrdersOrderMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiOrdersOrder>>, TError,{order: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiOrdersOrder>>, TError,{order: number}, TContext> => {
    
const mutationKey = ['deleteApiOrdersOrder'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiOrdersOrder>>, {order: number}> = (props) => {
          const {order} = props ?? {};

          return  deleteApiOrdersOrder(order,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiOrdersOrderMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiOrdersOrder>>>
    
    export type DeleteApiOrdersOrderMutationError = void

    /**
 * @summary Delete a specific order
 */
export const useDeleteApiOrdersOrder = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiOrdersOrder>>, TError,{order: number}, TContext>, fetch?: RequestInit}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiOrdersOrder>>,
        TError,
        {order: number},
        TContext
      > => {

      const mutationOptions = getDeleteApiOrdersOrderMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
